# Generated by Django 5.0.6 on 2024-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='hargabeli',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='barang',
            name='hargajual',
            field=models.IntegerField(),
        ),
    ]
